# Generated by Django 5.1.4 on 2024-12-19 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_curriculo_nome_alter_curriculo_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculo',
            name='curriculo_file',
            field=models.FileField(blank=True, null=True, upload_to='curriculos/'),
        ),
        migrations.AlterField(
            model_name='curriculo',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='curriculo',
            name='telefone',
            field=models.CharField(max_length=15),
        ),
    ]
